### ISSUE TITLE
Not working with meteor-admin

### ISSUE THREAD

**Issue by semeano** [lukemadera/meteor-autoform-googleplace#32]
I've setup my schema like this (coffeescript):

```
address:
  type: new SimpleSchema App.Schemas.Address
  autoform:
    afQuickFields:
      type: 'googleplace'
```

also tried this way:

```
address:
  type: new SimpleSchema App.Schemas.Address
  quickForm:
    type: 'googleplace'
```

even tried a simple field like this:

```
address:
  type: String
  autoform:
    afQuickField:
      type: 'googleplace'
```

and still nothing.

No errors, but also no autocomplete.
Can't figure out what I'm doing wrong...

Thanks!
